/** @file pbp_include.h Includes all luabindings plug-in headers */

/*
 **************************************************** 
 Convenience header file that includes all headers
 relevant to the pybindings plug-in. 

 (c) Thomas Moor 2023 - 2026
 ****************************************************
 */


#ifndef FAUDES_PBP_INCLUDE_H
#define FAUDES_PBP_INCLUDE_H



/**
 
@defgroup PybindingsPlugin Python Bindings Plug-In


@ingroup AllPlugins

<p>
This plug-in implements libFAUDES bindings for the scripting language Python; 
see http://www.python.org. Relevant libFAUDES data types and functions
can be accessed from the Python interpreter. The most convenient method
to make the faudes module available is to install it via <tt>pip<\tt>; i.e., for
Linux, macOS and Windows/MSYS
</p>

@code{.unparsed}
$ pip install faudes
$ python3 -c "import faudes; print(faudes.Version())"
@endcode

or, for native Windows

@code{.unparsed}
> py -m pip  install faudes
> py -c "import faudes; print(faudes.Version())"
@endcode

<p>
In the case of error messeges your platform/architecture is not supported by
our binary distrutions. Please let us know. Instructions on how to compile
your own binary are below.
</p>


<p>
Disclaimer: the primary scripting laguage for libFAUDES is Lua; see the Lua bindings plug-in.
Specifically, Lua bindings provide a more comprehensive interface, which is systematically
tested on a more regular basis. If you experience short commings of libFAUDES Python bindings,
please do not hesitate to report back to us.
</p>


@subsection SecPybindingsIntro1 Example Script

<p>
In large, libFAUDES Python bindings follow the same conventions as the Lua bindingins.
Thus, you may want to inspect the documentation of the latter. For further inspiration,
tutorials can be found at <tt>pybindings/tutorial</tt>.
</p>

<p>
For the following example, run Python in/from a directoty in which the
libFAUDES bindings reside (files <tt>_faudes.so</tt> and <tt>faudes.py</tt>).
</p>

@code{.unparsed}

# load libFAUDES bindings
import faudes

# test
faudes.Version()

# machine 1
gL1=faudes.Generator()
gL1.InsInitState("Idle")
gL1.SetMarkedState("Idle")
gL1.InsState("Busy")
gL1.InsEvent("alpha1")
gL1.InsEvent("beta1")
gL1.SetTransition("Idle","alpha1","Busy")
gL1.SetTransition("Busy","beta1","Idle")

# machine 2
gL2=faudes.Generator()
gL2.InsInitState("Idle")
gL2.SetMarkedState("Idle")
gL2.InsState("Busy")
gL2.InsEvent("alpha2")
gL2.InsEvent("beta2")
gL2.SetTransition("Idle","alpha2","Busy")
gL2.SetTransition("Busy","beta2","Idle")

# overall plant
gL=faudes.Generator()
faudes.Parallel(gL1,gL2,gL)

# controllable events
sCtrl=faudes.EventSet()
sCtrl.Insert("alpha1")
sCtrl.Insert("alpha2")

# specification aka buffer
gE=faudes.Generator()
gE.InsInitState("Empty")
gE.SetMarkedState("Empty")
gE.InsState("Full")
gE.InsEvent("beta1")
gE.InsEvent("alpha2")
gE.SetTransition("Empty","beta1","Full")
gE.SetTransition("Full","alpha2","Empty")

# lift specification to overall eventset
sAll=faudes.EventSet()
sAll=gL.Alphabet()
faudes.InvProject(gE,sAll)

# supremal closed loop
gK=faudes.Generator()
faudes.SupCon(gL,sCtrl,gE,gK)

# show result on console
gK.Write()

# save result as graphics
gK.GraphWrite("K.png")

@endcode

<p>
Note: for graphics output you must have installed <tt>dot</tt> from the GraphViz package.
If <tt>dot</tt> is not in the systems path, you may direct libfaudes via
<tt>faudes.DocExecPath("/wherever_dot_is/dot")</tt>.
</p>



@subsection SecPybindingsIntro3 Building the libFAUDES Python module

<p>
The faudes Python module consists of the glue code <tt>faudes.py</tt> and the
libFAUDES shrared object. By Python naming conventions, the latter is expected
as <tt>_faudes.so</tt> (or <tt>_faudes.pyd</tt> for Windows). Both files can be
generated by the libFAUDES build system; see
<a href="../faudes_build.html">build-system documentation</a> for details.
Manualy copying/renaming both files to a project folder enables the import of the
faudes module from Python scripts in that folder.
</p>

<p>
Example for the overall build process incl. copy/renbame:
<p>

@code{.unparsed}
./libFAUDES$ make dist-clean
./libFAUDES$ make -j configure
./libFAUDES$ make -j libfaudes
./libFAUDES$ cp plugings/pybindings/obj/faudes.py whereever/faudes.py
./libFAUDES$ cp libfaudes.so  whereever/_faudes.py
./libFAUDES$ cd whereever
./whereever$ python3 -c "import faudes; print(faudes.Version())"
@endcode

<p>
The libFAUDES build system also has a dediceted target <tt>pybindings-build</tt>
that utilises the Python module <tt>build</tt> to generate a Python package <tt>faudes-*.whl</tt>
for binary distribution. The latter can be installed via <tt>pip</tt>.
The benefit of this approach is that Python takes care of matching toolchains and
versions. The downside is that it wont use parallel jobs and therefore can take quite
some time. 
</p>

<p>
Example for the overall build process incl. installation:
<p>

@code{.unparsed}
./libFAUDES$ make dist-clean
./libFAUDES$ make configure
./libFAUDES$ make pybindings-wheel
./libFAUDES$ pip install faudes-2.34.0-cp314-cp314-macosx_10_15_universal2.whl
@endcode

<p>
Alternatively, you may download the configured source from PyPI and invoke <tt>build</tt>
directly; e.g. for Windows with official Python distribution an MSVC installed:
</p>
@code{.unparsed}
./faudes-2.34> py -m build --outdir=./
@endcode
</p>


@subsection PyLicense License

The Python bindings plug-in is distributed with libFAUDES. 
All code is  provided under terms of the LGPL. 


Copyright (c) 2023 - 2026 Thomas Moor.



*/



#endif
