name: Build libFAUDES with MSVC

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[a-z]*'
      
jobs:

  configure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: |
        make -j configure
        make clean
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sources
        path: ./
        if-no-files-found: error

  build:  

    runs-on: windows-latest
    needs: [configure]
    
<<<<<<< HEAD
=======
#    defaults:
#      run:
#        shell: cmd

>>>>>>> a5dea0c (Revert "win")
    steps:	
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: sources
        path: ./
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: UCRT64
        install: >-
          make
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Build Default Targets 
      shell: cmd
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win --touch includes
        %GNUMAKE% FAUDES_PLATFORM=cl_win libfaudes
        %GNUMAKE% FAUDES_PLATFORM=cl_win binaries
