name: Build libFAUDES with MSVC

on:
  workflow_dispatch:
      
jobs:

  configure-full:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: |
        export FAUDES_PLUGINS="synthesis luabindings pybindings"
        make -j configure
        make clean
        rm -rf ./bin/*
        echo "notempty" > ./obj/notempty
        echo "notempty" > ./bin/notempty
        tar -czf faudes.tgz ./*
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: faudes.tgz
        path: ./faudes.tgz
        if-no-files-found: error


  build-full:  

    runs-on: windows-latest
    needs: [configure-full]
    defaults:
      run:
        shell: cmd

    steps:	
    - name: Install MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Install MSYS
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: UCRT64
        install: >-
          make
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Pip for build
      uses: BSFishy/pip-action@v1
      with:
        packages: build
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: faudes.tgz
        path: ./
    - name: Extract Archive
      run: |
        tar -xzf faudes.tgz
        dir
    - name: Build DSO
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win report-platform
        %GNUMAKE% FAUDES_PLATFORM=cl_win -j1 libfaudes
        dir obj
        dir faudes.*
    - name: Build Tools
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win report-platform
        %GNUMAKE% FAUDES_PLATFORM=cl_win -j1 binaries
        dir bin
    - name: Build Wheel
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe
        %GNUMAKE% FAUDES_PLATFORM=cl_win report-platform
        %GNUMAKE% PYTHON=python FAUDES_PLATFORM=cl_win -j1 pybindings-wheel
        dir faudes.*
	python --version
    - uses: actions/upload-artifact@v4
      with:
        name: faudes.whl
        path: faudes-*.whl


  configure-nopy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: |
        export FAUDES_PLUGINS="synthesis luabindings"
        make -j configure
        make clean
        rm -rf ./bin/*
        echo "notempty" > ./obj/notempty
        echo "notempty" > ./bin/notempty
        tar -czf faudes-nopy.tgz ./*
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: faudes-nopy.tgz
        path: ./faudes-nopy.tgz
        if-no-files-found: error


  build-nopy:  

    runs-on: windows-latest
    needs: [configure-nopy]
    defaults:
      run:
        shell: cmd

    steps:	
    - name: Install MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Install MSYS
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: UCRT64
        install: >-
          make
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: faudes-nopy.tgz
        path: ./
    - name: Extract Archive
      run: |
        tar -xzf faudes-nopy.tgz
        dir
    - name: Build Static Libray 
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win report-platform
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 libfaudes
        dir obj
        dir 
    - name: Build Tools
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 binaries
        dir bin
    - name: Built Tutorial
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win -j1 tutorial
    - name: Run Test Cases
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win -j1 test


