name: Build libFAUDES on Linux

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
          . ./VERSION
          echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV" 
          echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV" 
    - name: Configure libFAUDES v${{ env.VMAJOR }}_${{ env.VMINOR }}
      run: make -j configure      
    - name: Build libFAUDES
      run: make -j
    - name: Build Tutorials
      run: make -j tutorial
    - name: Run Test Cases
      run: make test
    - name: Build Package
      run: make package
    - uses: actions/upload-artifact@v4
      with:
        name: libfaudes-${{ env.VMAJOR }}_${{ env.VMINOR }}.tar.gz
        path: ./libfaudes-*.tar.gz
        compression-level: 0
        if-no-files-found: error
