name: Build libFAUDES with MSVC

on:
  workflow_dispatch:
  push:
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:

  configure:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: >-
          base-devel
          gcc
          swig 
          perl 
          doxygen 
          ncurses-devel 
          libreadline-devel 
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: make -j configure
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: source
        path: ./
        compression-level: 0
        if-no-files-found: error

  build:  

    runs-on: windows-latest
    needs: [configure]
    
    defaults:
      run:
        shell: cmd

    steps:	
    - name: Download Artifact
      uses: actions/download-artifact@vV
      with:
        name: source
        path: ./
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Clean
      run: mingw-make clean
    - name: Build
      run: mingw-make -j
    
 
