name: Build libFAUDES with MSVC

on:
  workflow_dispatch:
      
jobs:

  configure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: |
        make -j configure
        make clean
        rm -rf ./bin/*
        echo "notempty" > ./obj/notempty
        echo "notempty" > ./bin/notempty
        tar -czf faudes.tgz ./*
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: faudes.tgz
        path: ./faudes.tgz
        if-no-files-found: error

  build:  

    runs-on: windows-latest
    needs: [configure]
    defaults:
      run:
        shell: cmd

    steps:	
    - name: Install Cl
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - name: Install MSYS
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        msystem: UCRT64
        install: >-
          make
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: faudes.tgz
        path: ./
    - name: Extract Archive
      run: |
        tar -xzf faudes.tgz
        dir
    - name: Build Static Libray 
      run: |
        dir
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 libfaudes
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 show
        dir obj
    - name: Build Tools
      run: |
        dir
        dir obj
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% --debug=b FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 binaries
        dir bin
    - name: Build Tutorials
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 tutorial
    - name: Run Test Cases
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win FAUDES_LINKING="static debug" -j1 test
    - name: Build DSO incl Tools
      run: |
        set GNUMAKE=${{ steps.msys2.outputs.msys2-location }}\usr\bin\make.exe 
        %GNUMAKE% FAUDES_PLATFORM=cl_win clean
        %GNUMAKE% FAUDES_PLATFORM=cl_win libfaudes
        %GNUMAKE% --debug=b FAUDES_PLATFORM=cl_win binaries
