name: Build libFAUDES on MSYS2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: >-
          base-devel
          gcc
          swig 
          perl 
          doxygen 
          ncurses-devel 
          libreadline-devel 
    - name: Figure Version
      run: |
          . ./VERSION
          echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
          echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
          gcc -dM -E src/cfl_platform.h
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: make -j1 configure
    - name: Build Default Targets
      run: make -j1
    - name: Build Tutorials
      run: make -j1 tutorial
    - name: Run Test Cases
      run: make -j1 test
