name: Build libFAUDES with MSVC

on:
  workflow_dispatch:
  push:
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:

  configure:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: >-
          base-devel
          gcc
          swig 
          perl 
          doxygen 
          ncurses-devel 
          libreadline-devel 
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: make -j configure
    - name: Have Source Archive
      run: |
         zip -x@src/TAR_EXCLUDES -9 -r source.zip ./
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: source.zip
        path: ./source.zip
        compression-level: 0
        if-no-files-found: error

  build:  needs

    runs-on: windows-latest
    needs: [configure]
    
    defaults:
      run:
        shell: cmd
	
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: source.zip
        path: ./source.zip
    - name: Show
      run: |
        dir
	unzip source.zip
      
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
 
