name: Build libFAUDES on MSYS2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          base-devel
          mingw-w64-ucrt-x86_64-gcc
          swig 
          perl 
          doxygen 
          ncurses-devel 
          libreadline-devel 
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Test Python
      run: |
        echo $PATH
        ls /ucrt64/bin
        pacman -Ss STRING
    - name: Pip for build
      uses: BSFishy/pip-action@v1
      with:
        packages: build
    - name: Figure Version
      run: |
          uname -a
          echo default msystem $MSYSTEM
          . ./VERSION
          echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
          echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: make -j1 configure PYTHON=python
    - name: Build Default Targets
      run: make -j1
    - name: Build Tutorials
      run: make -j1 tutorial
    - name: Run Test Cases
      run: make -j1 test
    - name: Build Package
      run: |
        make package
        ls -hl libfaudes_*.*
    - uses: actions/upload-artifact@v4
      with:
        name: libfaudes_${{ env.VMAJOR }}_${{ env.VMINOR }}.tar.gz
        path: ./libfaudes_*.tar.gz
        compression-level: 0
        if-no-files-found: error
