name: Build Pyhton Wheels

on:
  workflow_dispatch:

jobs:

  configure:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Figure Version
      run: |
        . ./VERSION
        echo "VMAJOR=$FAUDES_VERSION_MAJOR" >> "$GITHUB_ENV"
        echo "VMINOR=$FAUDES_VERSION_MINOR" >> "$GITHUB_ENV"
    - name: Configure libFAUDES v${{ env.VMAJOR }}.${{ env.VMINOR }}
      run: |
        make -j FAUDES_PLUGINS="synthesis omegaaut priorities observer diagnosis pybindings" configure
        make clean
        make pyproj
        tar -czf faudes.tgz ./*
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: faudes.tgz
        path: ./faudes.tgz
        if-no-files-found: error


  build_wheels:

    name: Build wheels on ${{ matrix.os }}
    needs: [configure]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
#        - os: linux-intel
#          runs-on: ubuntu-latest
#        - os: linux-arm
#          runs-on: ubuntu-24.04-arm
#        - os: windows-intel
#          runs-on: windows-latest
#        - os: windows-arm
#          runs-on: windows-11-arm
        - os: macos-arm
          runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: faudes.tgz
        path: ./
    - name: Extract Archive
      run: |
        tar -xzf faudes.tgz
    - name: Build wheels
      uses: pypa/cibuildwheel@v3.3.1
      with:
        package-dir: ./plugins/pybindings/pyproj
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl


  build_sdist:

    name: Build source distribution
    needs: [configure]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Build sdist
        run: |
          python3 -m build ./plugins/pybindings/pyproj --outdir=./ --sdist	
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: faudes-*.tar.gz


  publish:
  
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Show
        run: |
          ls
          ls dist      
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
  	  verbose: true
          repository-url: https://test.pypi.org/legacy/