name: C/C++ CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Extra Libs
      run: |
          sudo apt-get install doxygen swig
          sudo apt-get install libreadline-dev
    - name: Configure libFAUDES
      run: make configure
    - name: Build libFAUDES
      run: make
    - name: Run Test Cases
      run: make test
